version: '3.8'

services:
  web:
    build: .
    command: gunicorn game_ctrl.wsgi:application --bind 0.0.0.0:8000 --workers 3
    environment:
      - DJANGO_SETTINGS_MODULE=game_ctrl.settings.production
    user: app
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./logs:/app/logs
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db

  redis:
    image: redis:6-alpine
    user: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  postgres_data:
  redis_data: 