apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: registry.digitalocean.com/game-ctrl/web
            command: ["python", "manage.py", "backup_db"]
            envFrom:
            - secretRef:
                name: game-ctrl-secrets
          restartPolicy: OnFailure 