# Generated by Django 5.1.6 on 2025-02-15 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_created_controller_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
