# Generated by Django 5.1.6 on 2025-02-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_controller_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
